### ISSUE TITLE
Add Urdu translations

### ISSUE THREAD

**Issue by MuhammadShuaib** [ebraminio/switchdirection#1]
Here are urdu translations, plz add it, Thanks.

{
  "pageSwitchButton" : {
    "message": "تبدیل جہت صفحہ",
    "desciption": "Title of right-click menu button on pages"
  },
  "simpleSwitchButton" : {
    "message": "تبدیل جہت متن",
    "desciption": "Title of right-click menu button on edits"
  }
}

**Comment by ebraminio** [comment]
Hi Shoaib, nice to see you here :) I added the translation but honestly found the extension useless nowadays as Chrome is providing similar functionallity but some users say they can not see the Writing Mode or something like that on context menu on their editor. Cann't you see that also? Perhaps it is some kind of Chrome bug that some people see the option and some don't :(

**Comment by MuhammadShuaib** [comment]
Thanks.
Yeah brother, we are also facing such bug nowadays.
